compiler:
  solc:
    version: 0.8.20
    optimizer:
      enabled: true
      runs: 1  # 2**32 - 1
    evm_version: null
    viaIR: true

project_structure:
  contracts: contracts
  build: artifacts
  tests: test/py_tests

networks:
  default: hardhat
  hardhat:
    chain_id: 17
    accounts:
      - private_key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
        balance: 10000000000000000000000000000000000000000000000000000000
